openapi: 3.0.0
info:
  title: "Wikipedia Pageviews API"
  description: "An API to get pageview information from Wikipedia"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    TopArticlesItems:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TopArticlesByProject'
    TopArticlesByProject:
      type: object
      properties:
        project:
          type: string
        access:
          type: string
        timestamp_start:
          type: string
        timestamp_end:
          type: string
        articles:
          type: array
          items:
            $ref: '#/components/schemas/TopArticle'
    TopArticle:
      type: object
      properties:
        rank:
          type: integer
        article:
          type: string
        views:
          type: integer
    ArticleViewData:
      type: object
      properties:
        access:
          type: string
        agent:
          type: string
        article:
          type: string
        granularity:
          type: string
        project:
          type: string
        views:
          type: integer
    DayArticleViewData:
      allOf:
        - $ref: '#/components/schemas/ArticleViewData'
        - type: object
          properties:
            timestamp:
              type: string
    RangeArticleViewData:
      allOf:
        - $ref: '#/components/schemas/ArticleViewData'
        - type: object
          properties:
            timestamp_end:
              type: string
            timestamp_start:
              type: string
    Problem:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
        status:
          type: integer
        method:
          type: string
        uri:
          type: string

paths:
  /pageviews/{project}/top_articles_by_week/{startdate}:
    get:
      operationId: "pageviews.get_top_articles_by_week"
      summary: "Get the top 1000 articles ranked by pageview numbers for 7 days following a given start date."
      parameters:
        - name: project
          in: path
          description: "If you want to filter by project, use the domain of any Wikimedia project, for example 'en.wikipedia.org', 'www.mediawiki.org' or 'commons.wikimedia.org'."
          required: true
          schema:
            type: string
            default: "en.wikipedia.org"
        - name: startdate
          in: path
          description: "The first day of the week for which to retrieve top articles, in YYYYMMDD format."
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "A list of top articles ranked by page views."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopArticlesItems"
        default:
          description: "Unexpected Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
  /pageviews/{project}/top_articles_by_month/{yearmonth}:
    get:
      operationId: "pageviews.get_top_articles_by_month"
      summary: "Get the top 1000 articles ranked by pageview numbers for a given month."
      parameters:
        - name: project
          in: path
          description: "If you want to filter by project, use the domain of any Wikimedia project, for example 'en.wikipedia.org', 'www.mediawiki.org' or 'commons.wikimedia.org'."
          required: true
          schema:
            type: string
            default: "en.wikipedia.org"
        - name: yearmonth
          in: path
          description: "The year and month for which to retrieve top articles, in YYYYMM format."
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "A list of top articles ranked by page views."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopArticlesItems"
        default:
          description: "Unexpected Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
  /pageviews/{project}/article_views_by_week/{article}/{startdate}:
    get:
      operationId: "pageviews.get_article_views_by_week"
      summary: "Get the total number of views for a given article for 7 days following a given start date."
      parameters:
        - name: project
          in: path
          description: "If you want to filter by project, use the domain of any Wikimedia project, for example 'en.wikipedia.org', 'www.mediawiki.org' or 'commons.wikimedia.org'."
          required: true
          schema:
            type: string
            default: "en.wikipedia.org"
        - name: article
          in: path
          description: "'The title of any article in the specified project. Any spaces should be replaced with underscores. It also should be URI-encoded, so that non-URI-safe characters like %, / or ? are accepted. Example: Are_You_the_One%3F'."
          required: true
          schema:
            type: string
        - name: startdate
          in: path
          description: "The first day of the week to get views, in YYYYMMDD format."
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "The total view count"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RangeArticleViewData'
        default:
          description: "Unexpected Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
  /pageviews/{project}/article_views_by_month/{article}/{yearmonth}:
    get:
      operationId: "pageviews.get_article_views_by_month"
      summary: "Get the total number of views for a given article for a given month."
      parameters:
        - name: project
          in: path
          description: "If you want to filter by project, use the domain of any Wikimedia project, for example 'en.wikipedia.org', 'www.mediawiki.org' or 'commons.wikimedia.org'."
          required: true
          schema:
            type: string
            default: "en.wikipedia.org"
        - name: article
          in: path
          description: "'The title of any article in the specified project. Any spaces should be replaced with underscores. It also should be URI-encoded, so that non-URI-safe characters like %, / or ? are accepted. Example: Are_You_the_One%3F'."
          required: true
          schema:
            type: string
        - name: yearmonth
          in: path
          description: "The year and month to get views, in YYYYMM format."
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "The total view count"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RangeArticleViewData'
        default:
          description: "Unexpected Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
  /pageviews/{project}/article_top_day_in_month/{article}/{yearmonth}:
    get:
      operationId: "pageviews.get_article_top_day_in_month"
      summary: "Get the day in a given month when an article had the most views."
      parameters:
        - name: project
          in: path
          description: "If you want to filter by project, use the domain of any Wikimedia project, for example 'en.wikipedia.org', 'www.mediawiki.org' or 'commons.wikimedia.org'."
          required: true
          schema:
            type: string
            default: "en.wikipedia.org"
        - name: article
          in: path
          description: "'The title of any article in the specified project. Any spaces should be replaced with underscores. It also should be URI-encoded, so that non-URI-safe characters like %, / or ? are accepted. Example: Are_You_the_One%3F'."
          required: true
          schema:
            type: string
        - name: yearmonth
          in: path
          description: "The year and month to get views, in YYYYMM format."
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Article data with the date and number of views"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DayArticleViewData'
        default:
          description: "Unexpected Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"